In [2]:
import numpy as np

### Shallow copy

In [3]:
x = np.array([1, 2, 3])
y = x
z = np.copy(x)

In [6]:
x[0] = 10
print('y=', y)
print('z=', z)

y= [10  2  3]
z= [1 2 3]


### Deep copy
Shallow copy does not copy object elements within arrays

In [7]:
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
a

array([1, 'm', list([10, 3, 4])], dtype=object)

Use `copy.deepcopy()`

In [8]:
import copy
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
c = copy.deepcopy(a)
c[2][0] = 10
c

array([1, 'm', list([10, 3, 4])], dtype=object)

In [9]:
a

array([1, 'm', list([2, 3, 4])], dtype=object)