### Routines
Several exist here: https://numpy.org/doc/stable/reference/routines.array-creation.html?highlight=array%20creation%20routines    
Focus on the most used 

In [15]:
import numpy as np

### `ones`, `zeros`, `eye`, `diag` 

In [24]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Numbers in range

In [40]:
np.arange(3,13)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [57]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

### Work with generators `fromiter`

In [21]:
generator_expression = (i for i in range(10) if i % 2)

In [22]:
type(generator_expression)


generator

In [23]:
np.fromiter(generator_expression, dtype=int)

array([1, 3, 5, 7, 9])

###  Subset numpy arrays

In [3]:
x = [4 , 9 , 6, 3, 1]
y = np.array(x)
y[1]
high = y > 5
y[high]

array([9, 6])

In [5]:
print(y[high])

[9 6]
