In [2]:
import numpy as np

### Basics

In [3]:
ary = np.array([1,2,3,4,5])

In [5]:
ary[0]

array([1, 2, 3])

In [9]:
ary[:3] # equivalent to ary[0:3]

array([1, 2, 3])

In [34]:
ary2d = np.array([[1,2,3,3],[4,5,6,1],[2,52,36,1]])

In [37]:
ary2d

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  1],
       [ 2, 52, 36,  1]])

In [18]:
ary2d[1,2]

6

In [19]:
ary2d[1]

array([4, 5, 6])

In [26]:
ary2d[0] # entire first row

array([1, 2, 3])

In [33]:
ary2d[:,0] # entire first column

array([1, 4])

In [43]:
ary2d[1:3,2:4] # bottom 2x2 

array([[ 6,  1],
       [36,  1]])

In [47]:
ary2d[:,:2] # first two columns

array([[ 1,  2],
       [ 4,  5],
       [ 2, 52]])