In [25]:
import numpy as np

### Universal functions
NumPy provides vectorized wrappers for performing element-wise operations implicitly via `ufuncs` – short for universal functions   
`ufuncs` are implemented in compiled C code and very fast and efficient compared to vanilla Python    
Checkout more details here: https://numpy.org/doc/stable/reference/ufuncs.html?highlight=ufuncs

#### Binary ufuncs
`add`, `subtract`, `divide`, `multiply`   

Using list comprehension:

In [31]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
[[cell+1 for cell in row] for row in lst] 

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

Using Numpy `add` ufunc

In [41]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
ary = np.array(lst)
ary = np.add(ary,1)
print(ary)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Also uses operator overloading with math symbols: `+,-,/,*,**`

In [42]:
ary = np.array(lst)
ary+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [44]:
(ary+1)**2

array([[  4,   9,  16],
       [ 25,  36,  49],
       [ 64,  81, 100]])

#### Unary ufuncs
Unary ufuncs: `log`, `log10`, `exp`, `sqrt`   
`reduce`: compute the sum or product of array element along a given axis. By default, axis=0 for rows.

In [50]:
np.add.reduce(ary) # sum along rows

array([12, 15, 18])

In [51]:
np.add.reduce(ary,axis=1) # sum along columns

array([ 6, 15, 24])

shorthands:  `add.reduce` = `sum`  


In [53]:
ary.sum(axis=1)

array([ 6, 15, 24])

In [55]:
np.sum(ary, axis=1) # equivalent to ary.sum(...)

array([ 6, 15, 24])

In [62]:
ary.sum() # sum over all elements of the array

45

##### Other unary ufuncs
- `mean`: computes the mean
- `std`: computes the standard deviation
- `var`: computes variance
- `np.sort`: sorts an array [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html)
- `np.argsort`: returns indices that would sort an array
- `np.min`: returns the minimum value of an array
- `np.max`: returns the maximum value of an array
- `np.argmin`: returns the index of the minimum value
- `np.argmax`: returns the index of the maximum value
- `np.array_equal`: returns if the two arrays have the same shape and elements

In [67]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
ary.mean(axis=0) 

array([4., 5., 6.])

In [83]:
ary_std = ary.std(axis=1)

In [82]:
ary_var = ary.var(axis=1) 

In [84]:
np.array_equal(ary_std**2,ary_var)

True

In [111]:
ary=np.array([[3,11,8],[10,9,209]])
ary

array([[  3,  11,   8],
       [ 10,   9, 209]])

In [103]:
np.sort(ary) # sort along the last axis, i.e. columns

array([[ 1,  3,  8],
       [ 2,  9, 10]])

In [101]:
np.sort(ary,axis=1) # sort along the columns

array([[ 1,  3,  8],
       [ 2,  9, 10]])

In [100]:
np.sort(ary,axis=0) # sort along the rows

array([[ 3,  1,  2],
       [10,  9,  8]])

In [106]:
np.sort(ary,axis=None) # sort along flatened array 

array([ 1,  2,  3,  8,  9, 10])

In [104]:
np.argsort(ary,axis=0) # sort along the rows

array([[0, 0, 1],
       [1, 1, 0]])

In [112]:

np.min(ary,axis=1) # find min along columns

array([3, 9])

In [113]:
np.max(ary,axis=0) # find max along rows

array([ 10,  11, 209])

In [117]:
np.argmax(ary, axis=0)

array([1, 0, 1])